//export const GET_EMPLOYEES = "GET_EMPLOYEES";

//action type to hide or show the side bar
export const SHOW_SIDE_BAR = 'SHOW_SIDE_BAR';
export const HIDE_SIDE_BAR = 'HIDE_SIDE_BAR';


//action types for adding new employee
export const ADD_NEW_EMPLOYEE_REQUESTED = 'ADD_NEW_EMPLOYEE_REQUESTED';
export const ADD_NEW_EMPLOYEE_SUCCESS = 'ADD_NEW_EMPLOYEE_SUCCESS';
export const ADD_NEW_EMPLOYEE_FAILED = 'ADD_NEW_EMPLOYEE_FAILED';

//action types for employees get request
export const GET_EMPLOYEES_REQUESTED = 'GET_EMPLOYEES_REQUESTED';
export const GET_EMPLOYEES_SUCCESS = 'GET_EMPLOYEES_SUCCESS';
export const GET_EMPLOYEES_FAILED = 'GET_EMPLOYEES_FAILED';


//for getEmployeeById request
export const GET_EMPLOYEE_BY_ID_REQUESTED = 'GET_EMPLOYEE_BY_ID_REQUESTED';
export const GET_EMPLOYEE_BY_ID_SUCCESS = 'GET_EMPLOYEE_BY_ID_SUCCESS';
export const GET_EMPLOYEE_BY_ID_FAILED = 'GET_EMPLOYEE_BY_ID_FAILED';



//action types for deleting employeeByID
export const DELETE_EMPLOYEE_BY_ID = 'DELETE_EMPLOYEE_BY_ID';
export const DELETE_EMPLOYEE_BY_ID_SUCCESS = 'DELETE_EMPLOYEE_BY_ID_SUCCESS';
export const DELETE_EMPLOYEE_BY_ID_FAILED = 'DELETE_EMPLOYEE_BY_ID_FAILED';